services:
  mediamtx:
    network_mode: "host"
    build:
      context: ./mediamtx
      dockerfile: Dockerfile
    # ports:
    #   - "8889:8889"
    #   - "1935:1935"
    #   - "9997:9997"
  web-frontend:
    ports:
      - "4173:4173"
    build:
      context: ./tiling-frontend
      dockerfile: Dockerfile
    volumes:
      - tiling_frontend_build:/usr/src/app/dist  
  live-stream:
    depends_on:
      active_stream_proxy:
        condition: service_started
    build:
      context: ./live-stream
      dockerfile: Dockerfile
    volumes:
      - tiling_frontend_build:/html
    env_file: .stream.env
  backend:
    env_file: .backend.env
    ports:
      - "8000:8000"
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/db:/usr/src/app/db
  # active-stream-proxy:
  #   build:
  #     context: ./active-stream-proxy
  #     dockerfile: Dockerfile
  #   depends_on:
  #     web-frontend:
  #       condition: service_completed_successfully
  #     mediamtx:
  #       condition: service_started
  #     backend:
  #       condition: service_started
volumes:
  mediamtx_recordings:
  tiling_frontend_build:
